@BASE_URL=http://localhost:6969

@ZIP_CODE=21000
@ID=3

### GET cities
GET {{BASE_URL}}/cities
Content-Type: application/json

### GET city by zip code
GET {{BASE_URL}}/cities/{{ZIP_CODE}}
Content-Type: application/json

### DELETE city by zip code
DELETE {{BASE_URL}}/cities/{{ZIP_CODE}}


### PUT city by zip code
PUT {{BASE_URL}}/cities/{{ZIP_CODE}}
Content-Type: application/json

{
  "name": "New Dijon"
}

### GET weather of city by zip code
GET {{BASE_URL}}/weather/{{ZIP_CODE}}
Content-Type: application/json

### POST weather for city by zip code
POST {{BASE_URL}}/cities/{{ZIP_CODE}}/weather
Content-Type: application/json

{
  "zipCode": "13001",
  "weather": "pluie"
}

### DELETE weather for city by zip code
DELETE {{BASE_URL}}/weather/{{ZIP_CODE}}
Content-Type: application/json

### GET information of city's weather by zip code and weather id
GET {{BASE_URL}}/cities/{{ZIP_CODE}}/weather/{{ID}}
Content-Type: application/json

### GET information of city's weather by weather id
GET {{BASE_URL}}/weather/{{ID}}
Content-Type: application/json

### POST create a city 
POST {{BASE_URL}}/cities
Content-Type: application/json

{
  "zipCode": "14001",
  "name": "Caen"
}